### ISSUE TITLE
Parameter type metadata not available for 'Main', use the @Injectable decorator

### ISSUE THREAD

**Issue by szepeshazi** [connorwyatt/Fluency-Injection#1] opened 2016-12-14 11:51 UTC
Using reflect-metadata 0.1.8, fluency-injection 1.1.1 and Typescript compiler 2.0.6. When trying to run the following example in the README.md 

```
import { Injectable, bootstrap } from 'fluency-injection';

@Injectable
class TestDependency {
  constructor() {}

  public sayHello() {
    console.log('Hello!');
  }
}

class Main {
  constructor(testDependency: TestDependency) {
    testDependency.sayHello();
  }
}

bootstrap(Main);
```
I get the following error message:

Error: Parameter type metadata not available for 'Main', use the @Injectable decorator.
    at getDependencies (node_modules\fluency-injection\src\main.js:40:15)
    at instantiateClass (node_modules\fluency-injection\src\main.js:78:28)
    at Object.bootstrap (node_modules\fluency-injection\src\main.js:6:12)
    at js\app.js:36:25
    at js\app.js:12:17
    at Object.<anonymous> (js\app.js:17:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

Decorating the Main class with @Injectable solves the issue, but the Main class itself should not be an Injectable class.

**Comment by connorwyatt** [comment] 2016-12-14 13:08
@szepeshazi The reason it fails is that if you don't use a decorator in a file, Typescript doesn't output the metadata that is required by Reflect-Metadata to inject the params. Are your classes in different files?

**Comment by szepeshazi** [comment] 2016-12-14 13:58
@connorwyatt No, classes are in the same app.ts file. I was using the above snippet exactly as is.

**Comment by connorwyatt** [comment] 2016-12-14 14:22
@szepeshazi Ah okay, I will try to reproduce it tonight and get back to you once I know more. Thanks for raising it

**Comment by connorwyatt** [comment] 2016-12-24 22:13
Hi @szepeshazi,

I have recreated the issue can see that it is an issue with how Typescript outputs metadata.

My previous assumption (as I only ever use one class per file, and recommend that you do the same) was that Typescript outputs type metadata in the JS if there is at least one decorator in the file, however I can now see that it is on a per class basis.

What that means is that if you look at the JS output for the example, the main class does not have `__metadata('design:paramtypes', [])`, whereas the TestDependency does.

Unfortunately there is nothing that I can do in this library to counter that and so your options are to either use the `@Injectable` decorator on the Main class, or you can decorate the param with the `@Inject()` decorator like this:

```typescript
class Main {
  constructor(@Inject(TestDependency) testDependency: TestDependency) {
    testDependency.sayHello();
  }
}
```

I will add this as a known caveat in the documentation, however it will be the same with Angular2 (which is the inspiration behind the naming and usage), it's just that everything in ng2 has a decorator on it (either @Component, @Directive or @Injectable.

Your only other alternative is to create an empty decorator called @Application or something and then apply that to the Main class (It doesn't do anything that the @Injectable decorator doesn't but it makes it slightly more semantic if that is your concern).

Once the documentation is updated, I will close this issue as it relates to a 3rd party tool.

Sorry for the delay in getting back to you.

Merry Christmas

**Comment by connorwyatt** [comment] 2016-12-24 22:20
@szepeshazi Just as a further comment, you mentioned the following:

> Decorating the Main class with @Injectable solves the issue, but the Main class itself should not be an Injectable class.

And I disagree, the Main class _should_ be decorated with `@Injectable` as it states that the class can have dependencies injected into it, hence it is injectable. It doesn't mean that the Main class can be injected.

**Closed as completed** 2016-12-24 22:24 UTC
